# Generated by Django 2.2.9 on 2021-01-17 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210109_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Write a description for the group here.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text="Please write an ending of the group's web adress like www.blog.ru/group/<em>your_adress</em> (limit 200 characters).", max_length=200, unique=True, verbose_name='page adress'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Please write a title of the group (limit 200 characters).', max_length=200, verbose_name='the title of the group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Please choose an author of the post.', on_delete=django.db.models.deletion.CASCADE, related_name='post_set_author', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Please choose the post's group if you want.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_set_group', to='posts.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text="Don't hesitate, just write what you think.", verbose_name='text'),
        ),
    ]
