# Generated by Django 2.2.6 on 2021-02-06 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210202_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Напишите описание группы', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Пожалуйста, укажите окончание ссылки на группу вида: www.blog.ru/group/<em>имя группы</em> (ограничение 200 символов на латинице', max_length=200, unique=True, verbose_name='ссылка на группу'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Пожалуйста, укажите название группы (ограничение 200 символов).', max_length=200, verbose_name='название группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Укажите автора поста.', on_delete=django.db.models.deletion.CASCADE, related_name='posts_set_author', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Если хотите, можете выбрать принадлежность к группе.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_set_group', to='posts.Group', verbose_name='группа'),
        ),
    ]
