# Generated by Django 2.2.6 on 2021-02-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210206_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Пожалуйста, укажите окончание ссылки на группу вида: www.blog.ru/group/<em>имя группы</em> (ограничение 200 символов на латинице)', max_length=200, unique=True, verbose_name='ссылка на группу'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Пожалуйста, укажите название группы (ограничение 200 символов)', max_length=200, verbose_name='название группы'),
        ),
    ]
